name = "vre"
pages_build_output_dir = "./build/client"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-04-18"

[[kv_namespaces]]
binding="SESSION"
id="7948d47ca3a34c00b810a958ffb79b3d"